/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

import Controller.Jogo;
import static views.TelaPrincipal.jPAreaTrabalho;
import cardPokemon.*;
//import com.jgoodies.looks.plastic.PlasticLookAndFeel;
//import com.jgoodies.looks.plastic.theme.DarkStar;
//import com.jgoodies.looks.plastic.theme.DesertGreen;
//import com.jgoodies.looks.plastic.theme.ExperienceRoyale;
import java.awt.SystemColor;
import java.awt.Toolkit;
import java.io.FileNotFoundException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JInternalFrame;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;

/**
 * Classe por inicializar a interface grafica do Jogo.
 *
 * @author Douglas
 */
public class TelaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form TelaPrincipal
     */
    
    public static MenuMeusPokemons exibirMeusPokemons = null;
    public static MenuExibirTodosPokemons exibirTodosPokemons = null;
    public static MenuGinasios exibirGinasios = null;
    public static MenuInicial menu = null;
    public static Jogo batalhaPokemon;

    
    public TelaPrincipal() {
        this.setUndecorated(true);// remove barra de titulo
        //this.setAlwaysOnTop(true); // nao permite ser minimizado

        initComponents();
        
        
        Toolkit tk = Toolkit.getDefaultToolkit();
            int xsize = (int)tk.getScreenSize().getWidth();
            int ysize = (int)tk.getScreenSize().getHeight();
            
        this.setSize(xsize, ysize);
        
        this.iniciarJogo();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

        jMenu3 = new javax.swing.JMenu();
        jDialog1 = new javax.swing.JDialog();
        jPAreaTrabalho = new javax.swing.JDesktopPane();

        jMenu3.setText("jMenu3");

        javax.swing.GroupLayout jDialog1Layout = new javax.swing.GroupLayout(jDialog1.getContentPane());
        jDialog1.getContentPane().setLayout(jDialog1Layout);
        jDialog1Layout.setHorizontalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jDialog1Layout.setVerticalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setSize(new java.awt.Dimension(0, 0));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        org.jdesktop.beansbinding.Binding binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, jPAreaTrabalho, org.jdesktop.beansbinding.ELProperty.create("${maximumSize}"), jPAreaTrabalho, org.jdesktop.beansbinding.BeanProperty.create("maximumSize"));
        bindingGroup.addBinding(binding);

        javax.swing.GroupLayout jPAreaTrabalhoLayout = new javax.swing.GroupLayout(jPAreaTrabalho);
        jPAreaTrabalho.setLayout(jPAreaTrabalhoLayout);
        jPAreaTrabalhoLayout.setHorizontalGroup(
            jPAreaTrabalhoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 607, Short.MAX_VALUE)
        );
        jPAreaTrabalhoLayout.setVerticalGroup(
            jPAreaTrabalhoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 434, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPAreaTrabalho)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPAreaTrabalho)
        );

        bindingGroup.bind();

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened

        //ALTERANDO O PADRAO DE COR DO PROJETO
        //SkyBlue()
        //BrownSugar()
        // DarkStar()  
        //DesertGreen()
        //Silver()
        //ExperienceRoyale()
        
//                  try {
//            PlasticLookAndFeel.setPlasticTheme(new DarkStar());
//                  try {
//                      UIManager.setLookAndFeel("com.jgoodies.looks.plastic.Plastic3DLookAndFeel");
//                  } catch (InstantiationException ex) {
//                      Logger.getLogger(jPAreaTrabalho.getName()).log(Level.SEVERE, null, ex);
//                  } catch (IllegalAccessException ex) {
//                      Logger.getLogger(jPAreaTrabalho.getName()).log(Level.SEVERE, null, ex);
//                  } catch (UnsupportedLookAndFeelException ex) {
//                      Logger.getLogger(jPAreaTrabalho.getName()).log(Level.SEVERE, null, ex);
//                  }
//           
//
//        } catch (ClassNotFoundException ex) {
//            ex.printStackTrace();
//        }
//    SwingUtilities.updateComponentTreeUI(this);
//
// jPAreaTrabalho.setBackground(SystemColor.BLACK);
        
        
    }//GEN-LAST:event_formWindowOpened
    
    
    public void iniciarJogo() {
        
    try{ 
           
            this.batalhaPokemon = new Jogo();

            List<CarD> iniciais = this.batalhaPokemon.getCartasDisponiveis();

            Cadastro cadastrando = new Cadastro(Arrays.asList(
                iniciais.get(0),iniciais.get(3),iniciais.get(6)));

            jPAreaTrabalho.add(cadastrando);
            cadastrando.setVisible(true);
            
            
       }catch(Exception e)
       {
            
               JOptionPane.showMessageDialog(null, "Erro ao carregar o jogo!"+e.getMessage(), null, 0);
        
           System.exit(0);
       }

        
    }

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDialog jDialog1;
    private javax.swing.JMenu jMenu3;
    public static javax.swing.JDesktopPane jPAreaTrabalho;
    private org.jdesktop.beansbinding.BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables
}
