/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import static View.TelaPrincipal.batalhaPokemon;
import static View.TelaPrincipal.exibirGinasios;
import static View.TelaPrincipal.exibirMeusPokemons;
import static View.TelaPrincipal.jPAreaTrabalho;
import javafx.application.Application;
import static View.TelaPrincipal.exibirTodosPokemons;
import java.awt.Toolkit;

/**
 *
 * @author douglas.silva
 */
public class MenuInicial extends javax.swing.JInternalFrame {

    /**
     * Creates new form MenuInicial
     */

    
    public MenuInicial() {
        
        //this.setUndecorated(true);// remove barra de titulo
        //this.setAlwaysOnTop(true); // 
        
        initComponents();
        
        Toolkit tk = Toolkit.getDefaultToolkit();
            int xsize = (int)tk.getScreenSize().getWidth();
            int ysize = (int)tk.getScreenSize().getHeight();
            
        this.setSize(xsize, ysize);
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jBtnBatalhar = new javax.swing.JButton();
        jBtnMeusPokemons = new javax.swing.JButton();
        jBtnPokemons = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane2.setViewportView(jTextArea1);

        setBorder(null);
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameActivated(evt);
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
            }
        });

        jPanel1.setLayout(null);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jLabel2.setText("BATALHA CARTAS POKEMON");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(80, 30, 730, 50);

        jBtnBatalhar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jBtnBatalhar.setText("Batalhar ");
        jBtnBatalhar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnBatalharActionPerformed(evt);
            }
        });
        jPanel1.add(jBtnBatalhar);
        jBtnBatalhar.setBounds(480, 150, 302, 110);

        jBtnMeusPokemons.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jBtnMeusPokemons.setText("Meus Pokemons");
        jBtnMeusPokemons.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnMeusPokemonsActionPerformed(evt);
            }
        });
        jPanel1.add(jBtnMeusPokemons);
        jBtnMeusPokemons.setBounds(50, 150, 390, 50);

        jBtnPokemons.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jBtnPokemons.setText("Pokemons");
        jBtnPokemons.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnPokemonsActionPerformed(evt);
            }
        });
        jPanel1.add(jBtnPokemons);
        jBtnPokemons.setBounds(50, 210, 390, 50);

        jButton5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton5.setText("Fechar Jogo");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton5);
        jButton5.setBounds(50, 280, 730, 50);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setText("Treinador:");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(50, 110, 100, 22);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("NomeJogador");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(150, 110, 150, 22);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(31, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 826, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(56, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(100, 100, 100)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 336, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(134, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBtnPokemonsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnPokemonsActionPerformed

        exibirTodosPokemons = new MenuExibirTodosPokemons();
        jPAreaTrabalho.add(exibirTodosPokemons);
        exibirTodosPokemons.setVisible(true);
        this.setVisible(false);
        
    }//GEN-LAST:event_jBtnPokemonsActionPerformed

    private void formInternalFrameActivated(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameActivated
        // TODO add your handling code here:
        if(batalhaPokemon.getPlayer()!= null)
        jLabel1.setText(batalhaPokemon.getPlayer().getNome());
        
        else
            jLabel1.setText("jogador nao criado");
        
        
    }//GEN-LAST:event_formInternalFrameActivated

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        //this.setVisible(false);
        
        System.exit(0);
        
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jBtnMeusPokemonsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnMeusPokemonsActionPerformed
        // TODO add your handling code here:
        exibirMeusPokemons = new MenuMeusPokemons();
        jPAreaTrabalho.add(exibirMeusPokemons);
        exibirMeusPokemons.setVisible(true);

        this.setVisible(false);
      
    }//GEN-LAST:event_jBtnMeusPokemonsActionPerformed

    private void jBtnBatalharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnBatalharActionPerformed
        // TODO add your handling code here:
        
        exibirGinasios = new MenuGinasios();
        jPAreaTrabalho.add(exibirGinasios);
        exibirGinasios.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jBtnBatalharActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnBatalhar;
    private javax.swing.JButton jBtnMeusPokemons;
    private javax.swing.JButton jBtnPokemons;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
}
