/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import static View.TelaPrincipal.batalhaPokemon;
import static View.TelaPrincipal.exibirGinasios;
import static View.TelaPrincipal.exibirMeusPokemons;
import static View.TelaPrincipal.jPAreaTrabalho;
import javafx.application.Application;
import static View.TelaPrincipal.exibirTodosPokemons;

/**
 *
 * @author douglas.silva
 */
public class MenuInicial extends javax.swing.JInternalFrame {

    /**
     * Creates new form MenuInicial
     */

    
    public MenuInicial() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jBtnBatalhar = new javax.swing.JButton();
        jBtnMeusPokemons = new javax.swing.JButton();
        jBtnPokemons = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane2.setViewportView(jTextArea1);

        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameActivated(evt);
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
            }
        });

        jBtnBatalhar.setText("Batalhar ");
        jBtnBatalhar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnBatalharActionPerformed(evt);
            }
        });

        jBtnMeusPokemons.setText("Meus Pokemons");
        jBtnMeusPokemons.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnMeusPokemonsActionPerformed(evt);
            }
        });

        jBtnPokemons.setText("Pokemons");
        jBtnPokemons.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnPokemonsActionPerformed(evt);
            }
        });

        jLabel1.setText("NomeJogador");

        jButton5.setText("Fechar Jogo");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("BATALHA CARTAS POKEMON");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jBtnBatalhar, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jBtnPokemons, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 302, Short.MAX_VALUE))
                .addContainerGap(44, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(47, 47, 47)
                    .addComponent(jBtnMeusPokemons, javax.swing.GroupLayout.PREFERRED_SIZE, 305, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(42, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(47, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(34, 34, 34)
                .addComponent(jLabel1)
                .addGap(45, 45, 45)
                .addComponent(jBtnBatalhar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jBtnPokemons)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton5)
                .addGap(29, 29, 29))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(126, 126, 126)
                    .addComponent(jBtnMeusPokemons)
                    .addContainerGap(129, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBtnPokemonsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnPokemonsActionPerformed

        exibirTodosPokemons = new MenuExibirTodosPokemons();
        jPAreaTrabalho.add(exibirTodosPokemons);
        exibirTodosPokemons.setVisible(true);
        this.setVisible(false);
        
    }//GEN-LAST:event_jBtnPokemonsActionPerformed

    private void formInternalFrameActivated(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameActivated
        // TODO add your handling code here:
        if(batalhaPokemon.getPlayer()!= null)
        jLabel1.setText(batalhaPokemon.getPlayer().getNome());
        
        else
            jLabel1.setText("jogador nao criado");
        
        
    }//GEN-LAST:event_formInternalFrameActivated

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        //this.setVisible(false);
        
        System.exit(0);
        
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jBtnMeusPokemonsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnMeusPokemonsActionPerformed
        // TODO add your handling code here:
        exibirMeusPokemons = new MenuMeusPokemons();
        jPAreaTrabalho.add(exibirMeusPokemons);
        exibirMeusPokemons.setVisible(true);

        this.setVisible(false);
      
    }//GEN-LAST:event_jBtnMeusPokemonsActionPerformed

    private void jBtnBatalharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnBatalharActionPerformed
        // TODO add your handling code here:
        
        exibirGinasios = new MenuGinasios();
        jPAreaTrabalho.add(exibirGinasios);
        exibirGinasios.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jBtnBatalharActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnBatalhar;
    private javax.swing.JButton jBtnMeusPokemons;
    private javax.swing.JButton jBtnPokemons;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
}
