/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import static View.TelaPrincipal.batalhaPokemon;
import static View.TelaPrincipal.menu;
import cardPokemon.CarD;
import cardPokemon.Duelo;

import cardPokemon.Ginasio;
import cardPokemon.Jogador;
import java.awt.Toolkit;
import java.util.ArrayList;
import java.util.List;
import java.util.Random;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;

/**
 *
 * @author douglas.silva
 */
public class MenuGinasios extends javax.swing.JInternalFrame {

    /**
     * Creates new form MenuGinasios
     */
    private List<Jogador> treinadores;
    private List<Ginasio> listaGinasios;

    public MenuGinasios() {

        this.listaGinasios = batalhaPokemon.getGinasios();

        initComponents();
                Toolkit tk = Toolkit.getDefaultToolkit();
            int xsize = (int)tk.getScreenSize().getWidth();
            int ysize = (int)tk.getScreenSize().getHeight();
            
        this.setSize(xsize, ysize);
        
        
        
        this.carregarComboBox();

    }

    public void carregarComboBox() {

        DefaultComboBoxModel comboModelGinasio = (DefaultComboBoxModel) this.jComboBox1.getModel();
        comboModelGinasio.removeAllElements();

        comboModelGinasio.addElement("---Selecione um Ginasio---");
        for (Ginasio ginasio : listaGinasios) {
            comboModelGinasio.addElement(ginasio.getNome());

        }
    }

    public void carregarJTable() {
        try {
            if (this.jComboBox1.getSelectedIndex() > 0) {

                Ginasio g = listaGinasios.get(this.jComboBox1.getSelectedIndex() - 1);

                this.jLabel3.setText(Integer.toString(g.getNivel()));
                this.treinadores = g.getAdversarios();

                TabelaGinasio model = new TabelaGinasio(this.treinadores);
                this.jTable1.setModel(model);

            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Erro combo" + e.toString());
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jCheckBoxMenuItem1 = new javax.swing.JCheckBoxMenuItem();
        jButton1 = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox<>();
        jSeparator1 = new javax.swing.JSeparator();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();

        jCheckBoxMenuItem1.setSelected(true);
        jCheckBoxMenuItem1.setText("jCheckBoxMenuItem1");

        setBorder(null);
        setClosable(true);
        setToolTipText("");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setText("BATALHAR");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 58, 131, 105));

        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(59, 11, 194, -1));
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 174, 471, 10));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Pokemon", "Vida", "Ataque"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 58, 302, 105));

        jLabel1.setText(" Level:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 38, -1, -1));

        jButton2.setText("VOLTAR");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(321, 297, 160, -1));

        jLabel2.setText("Ginasios");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 14, -1, -1));

        jLabel3.setText("Oponente");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(59, 38, -1, -1));

        jTextArea1.setEditable(false);
        jTextArea1.setBackground(new java.awt.Color(153, 153, 153));
        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jTextArea1.setCursor(new java.awt.Cursor(java.awt.Cursor.E_RESIZE_CURSOR));
        jTextArea1.setDropMode(javax.swing.DropMode.INSERT);
        jTextArea1.setNextFocusableComponent(jComboBox1);
        jScrollPane2.setViewportView(jTextArea1);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, 471, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        jTextArea1.setText("");
//        this.batalharView(listaGinasios.get(jComboBox1.getSelectedIndex()-1));
        Ginasio g = listaGinasios.get(jComboBox1.getSelectedIndex() - 1);

        try {
            batalhaPokemon.batalharGinasio(g, jTextArea1);
        } catch (InterruptedException ex) {
            Logger.getLogger(MenuGinasios.class.getName()).log(Level.SEVERE, null, ex);
        }

//        JOptionPane.showMessageDialog(null, "Fim da batalha");

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:

        this.setVisible(false);
        menu.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:

        //if(!this.jComboBox1.getSelectedItem().equals("---Selecione um Ginasio---"));
        this.carregarJTable();
    }//GEN-LAST:event_jComboBox1ActionPerformed

    void batalharView(Ginasio g) {
        //INICIAR A BATALHA

        System.out.println("\ns#### ENTRANDO NO GINASIO " + g.getNome() + " ####");

        for (int i = 0; i < g.getAdversarios().size(); i++) {
            System.out.println("###################################### DUELO ##########################################");
            System.out.println(
                    "[" + batalhaPokemon.getPlayer().getNome() + " - " + batalhaPokemon.getPlayer().getPokemonPrincipal().getNome() + "] "
                    + "X"
                    + " [" + g.getAdversarios().get(i).getNome() + " - " + g.getAdversarios().get(i).getPokemonPrincipal().getNome() + "]");

            System.out.println("############");

            //Main.pausarAplicacao();
            Duelo combate = new Duelo(batalhaPokemon.getPlayer(), g.getAdversarios().get(i));
//            combate.duelarInstantaneo();

            if (combate.getVencedor() != -1) {
                if (combate.getVencedor() == 1) {
                    System.out.println("Parabens você venceu a batalha!");
                    JOptionPane.showMessageDialog(null, "Parabens você venceu a batalha!");
                    batalhaPokemon.getPlayer().getCardPrincipal().addExperiencia(batalhaPokemon.getExpericenciaPorVitoria(), (ArrayList<CarD>) batalhaPokemon.getCartasDisponiveis());
                    //Main.pausarAplicacao();

                } else if (combate.getVencedor() == 0) {
                    System.out.println("\nQue pena, voce foi derrotado adversario " + g.getAdversarios().get(i).getNome());
                    JOptionPane.showMessageDialog(null, "\nQue pena, voce foi derrotado adversario " + g.getAdversarios().get(i).getNome());
                    batalhaPokemon.getPlayer().getCardPrincipal().addExperiencia(((int) -batalhaPokemon.getExpericenciaPorVitoria() / 4), (ArrayList<CarD>) batalhaPokemon.getCartasDisponiveis());

                    // Main.pausarAplicacao();
                    break;
                }
            }
            if (combate.getVencedor() == 1 && i == g.getAdversarios().size() - 1) {
                System.out.println("Parabens você venceu todos os adversarios!");
                JOptionPane.showMessageDialog(null, "Parabens você venceu todos os adversarios!");
                // Main.pausarAplicacao(); 
                this.premioVitoriaInstatanea(g.getAdversarios());
            }
            // Main.pausarAplicacao();
        }
    }

    public void premioVitoriaInstatanea(List<Jogador> adversarios) {
        Random r = new Random();
        batalhaPokemon.getPlayer().addDeckPokemon(adversarios.get(r.nextInt(adversarios.size())).getCardPrincipal().createNewCardPokemon());

    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem1;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
}
